// Set the current user data
export const SET_CURRENT_USER_PROFILE = "SET_CURRENT_USER_PROFILE";
export const SET_CURRENT_USER_PROFILE_TYPE = "SET_CURRENT_USER_PROFILE_TYPE";

// Get the current user data
export const GET_CURRENT_USER_PROFILE = "GET_CURRENT_USER_PROFILE";

// Update the current user data
export const UPDATE_CURRENT_USER_PROFILE = "UPDATE_CURRENT_USER_PROFILE";
export const UPDATE_CURRENT_USER_PROFILE_IMAGE =
  "UPDATE_CURRENT_USER_PROFILE_IMAGE";
export const UPDATE_CURRENT_USER_PROFILE_FIRST_NAME =
  "UPDATE_CURRENT_USER_PROFILE_FIRST_NAME";
export const UPDATE_CURRENT_USER_PROFILE_LAST_NAME =
  "UPDATE_CURRENT_USER_PROFILE_LAST_NAME";

export const REFETCH_CURRENT_USER_PROFILE = "REFETCH_CURRENT_USER_PROFILE";
export const RESET_CURRENT_USER_PROFILE = "RESET_CURRENT_USER_PROFILE";
