// Set the current user data
export const SET_CURRENT_USER_PROFILE = "SET_CURRENT_USER_PROFILE";
export const SET_CURRENT_USER_PROFILE_TYPE = "SET_CURRENT_USER_PROFILE_TYPE";

// Set the temp user data
export const SET_TEMP_USER_PROFILE_FULL_NAME =
  "SET_TEMP_USER_PROFILE_FULL_NAME";
export const SET_TEMP_USER_PROFILE_GENDER = "SET_TEMP_USER_PROFILE_GENDER";
export const SET_TEMP_USER_PROFILE_BIO = "SET_TEMP_USER_PROFILE_BIO";

// Set settings state
export const SET_SETTINGS_FULL_NAME = "SET_SETTINGS_FULL_NAME";

// Get the current user data
export const GET_CURRENT_USER_PROFILE = "GET_CURRENT_USER_PROFILE";

// Update the current user data
export const UPDATE_CURRENT_USER_PROFILE = "UPDATE_CURRENT_USER_PROFILE";
export const UPDATE_CURRENT_USER_PROFILE_IMAGE =
  "UPDATE_CURRENT_USER_PROFILE_IMAGE";
export const UPDATE_CURRENT_USER_PROFILE_FIRST_NAME =
  "UPDATE_CURRENT_USER_PROFILE_FIRST_NAME";
export const UPDATE_CURRENT_USER_PROFILE_LAST_NAME =
  "UPDATE_CURRENT_USER_PROFILE_LAST_NAME";

export const UPDATE_CURRENT_USER_PROFILE_FULL_NAME =
  "UPDATE_CURRENT_USER_PROFILE_FULL_NAME";

export const REFETCH_CURRENT_USER_PROFILE = "REFETCH_CURRENT_USER_PROFILE";
export const RESET_CURRENT_USER_PROFILE = "RESET_CURRENT_USER_PROFILE";
